name: Build docker images

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  # version that would be tagged as latest
  LATEST_VERSION: 14.21.3

jobs:
  build:
    strategy:
      matrix:
        versions: [
          { node: 14.21.3, alpine: 3.16 },
          { node: 16.20.0, alpine: 3.18 },
          { node: 18.18.2, alpine: 3.18 },
        ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          path: packages/alpine-node-nginx/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: alfabankui/arui-scripts
          build_args: NODE_VERSION=${{ matrix.versions.node }},ALPINE_VERSION=${{ matrix.versions.alpine }}
          tags: ${{ matrix.versions.node == env.LATEST_VERSION && format('{0},latest', matrix.versions.node) || matrix.version.node }}
